-- MySQL Script generated by MySQL Workbench
-- Wed Sep 21 11:25:54 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MDB` DEFAULT CHARACTER SET utf8 ;
USE `MDB` ;

-- -----------------------------------------------------
-- Table `MDB`.`Exampoints`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MDB`.`Exampoints` (
  `Maths` INT NOT NULL,
  `Russian` INT NOT NULL,
  `Social` INT NOT NULL,
  `ID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MDB`.`Listofapplicants`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MDB`.`Listofapplicants` (
  `Fullname` VARCHAR(50) NOT NULL,
  `DateofBirth` DATE NOT NULL,
  `Graduationdate` DATE NOT NULL,
  `Passport` INT NOT NULL,
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Socialcategory_ID` INT NOT NULL,
  `Exampoints_ID` INT NOT NULL,
  `Listofspecialties_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Listofapplicants_Socialcategory1_idx` (`Socialcategory_ID` ASC) VISIBLE,
  INDEX `fk_Listofapplicants_Exampoints1_idx` (`Exampoints_ID` ASC) VISIBLE,
  INDEX `fk_Listofapplicants_Listofspecialties1_idx` (`Listofspecialties_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Listofapplicants_Socialcategory1`
    FOREIGN KEY (`Socialcategory_ID`)
    REFERENCES `MDB`.`Socialcategory` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Listofapplicants_Exampoints1`
    FOREIGN KEY (`Exampoints_ID`)
    REFERENCES `MDB`.`Exampoints` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Listofapplicants_Listofspecialties1`
    FOREIGN KEY (`Listofspecialties_ID`)
    REFERENCES `MDB`.`Listofspecialties` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MDB`.`Listofspecialties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MDB`.`Listofspecialties` (
  `specialties` VARCHAR(50) NOT NULL,
  `Numberofseats` INT NOT NULL,
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Settype_ID` INT NOT NULL,
  `Passingscore` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Listofspecialties_Settype1_idx` (`Settype_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Listofspecialties_Settype1`
    FOREIGN KEY (`Settype_ID`)
    REFERENCES `MDB`.`Settype` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MDB`.`Settype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MDB`.`Settype` (
  `Settype` VARCHAR(50) NOT NULL,
  `ID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MDB`.`Socialcategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MDB`.`Socialcategory` (
  `Socialcategory` VARCHAR(50) NOT NULL,
  `Priority` INT NOT NULL,
  `ID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `MDB`.`Listofapplicants`
-- -----------------------------------------------------
START TRANSACTION;
USE `MDB`;
INSERT INTO `MDB`.`Listofapplicants` (`Fullname`, `DateofBirth`, `Graduationdate`, `Passport`, `ID`, `Socialcategory_ID`, `Exampoints_ID`, `Listofspecialties_ID`) VALUES ('Александрюк Юлия Андреевна', '02.03.2004', '01.06.2022', 3464, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `MDB`.`Listofapplicants` (`Fullname`, `DateofBirth`, `Graduationdate`, `Passport`, `ID`, `Socialcategory_ID`, `Exampoints_ID`, `Listofspecialties_ID`) VALUES ('Алексеева Ирина Сергеевна', '02.05.2004', '01.06.2022', 5788, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `MDB`.`Listofapplicants` (`Fullname`, `DateofBirth`, `Graduationdate`, `Passport`, `ID`, `Socialcategory_ID`, `Exampoints_ID`, `Listofspecialties_ID`) VALUES ('Гордин Григорий Валерьевич', '28.10.2004', '01.06.2022', 2322, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `MDB`.`Listofapplicants` (`Fullname`, `DateofBirth`, `Graduationdate`, `Passport`, `ID`, `Socialcategory_ID`, `Exampoints_ID`, `Listofspecialties_ID`) VALUES ('Ильченко Оксана Ивановна', '31.03.2005', '01.06.2022', 7689, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `MDB`.`Listofapplicants` (`Fullname`, `DateofBirth`, `Graduationdate`, `Passport`, `ID`, `Socialcategory_ID`, `Exampoints_ID`, `Listofspecialties_ID`) VALUES ('Колмукиди Светлана Валерьевна', '08.01.2004', '01.06.2022', 4574, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `MDB`.`Listofapplicants` (`Fullname`, `DateofBirth`, `Graduationdate`, `Passport`, `ID`, `Socialcategory_ID`, `Exampoints_ID`, `Listofspecialties_ID`) VALUES ('Колотова Анастасия Александровна', '24.07.2003', '01.06.2022', 5743, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `MDB`.`Listofapplicants` (`Fullname`, `DateofBirth`, `Graduationdate`, `Passport`, `ID`, `Socialcategory_ID`, `Exampoints_ID`, `Listofspecialties_ID`) VALUES ('Кутепова Вероника Валерьевна', '04.12.2004', '01.06.2022', 1111, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `MDB`.`Listofapplicants` (`Fullname`, `DateofBirth`, `Graduationdate`, `Passport`, `ID`, `Socialcategory_ID`, `Exampoints_ID`, `Listofspecialties_ID`) VALUES ('Мельник Софья Васильевна', '27.11.2004', '01.06.2022', 2423, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `MDB`.`Listofapplicants` (`Fullname`, `DateofBirth`, `Graduationdate`, `Passport`, `ID`, `Socialcategory_ID`, `Exampoints_ID`, `Listofspecialties_ID`) VALUES ('Полякова Анна Александровна', '10.10.2005', '01.06.2022', 5479, DEFAULT, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO `MDB`.`Listofapplicants` (`Fullname`, `DateofBirth`, `Graduationdate`, `Passport`, `ID`, `Socialcategory_ID`, `Exampoints_ID`, `Listofspecialties_ID`) VALUES ('Попов Владислав Вячеславович', '03.04.2003', '01.06.2022', 1212, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

COMMIT;

